name: GitHub-Profile-3D-Contrib

on:
  schedule:
    # Skrypt uruchomi się automatycznie raz dziennie o 18:00 UTC (czyli wieczorem czasu polskiego)
    - cron: "0 18 * * *"
  workflow_dispatch: # Ta opcja pozwala na ręczne uruchomienie skryptu kliknięciem

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Zbudowano nowe wieżowce w Git City"
          git push
