name: Play Tic-Tac-Toe

on:
  issues:
    types: [opened]
  workflow_dispatch: # Dodano: pozwala na ręczne wygenerowanie planszy

jobs:
  play:
    runs-on: ubuntu-latest
    name: Gra w Kółko i Krzyżyk
    steps:
      - uses: actions/checkout@v4
      
      - uses: basselalaraaj/readme-tic-tac-toe@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Zapisz zmiany w README
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Wykonano nowy ruch w kółko i krzyżyk" || exit 0
          git push
